openapi: "3.0.2"
info:
  title: SRIOVDP Values Schema
  description: This is for validating valuesSchema.
  version: "3.3.2"
servers:
  - url: 127.0.0.1:8000
paths:
  /sriov-dp:
    get:
      summary: Used for getting srio-vdp related values.
      description: Returns all sriov-dp related values.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SriovDPValues"

components:
  schemas:
    SriovDPValues:
      title: sriov-network-device-plugin.community.tanzu.vmware.com.3.3.2 values schema
      properties:
        namespace:
          type: string
          description: Namespace where sriov-network-device-plugin daemonset will be deployed.
          default: kube-system
        daemonset:
          type: object
          description: DaemonSet related configurations.
          properties:
            resources:
              type: object
              description: DaemonSet resources settings.
              properties:
                requests:
                  type: object
                  description: Requests for CPU and memory usage.
                  properties:
                    cpu:
                      type: string
                      description: Requests for CPU usage.
                      default: 250m
                    memory:
                      type: string
                      description: Requests for memory usage.
                      default: 40Mi
                limits:
                  type: object
                  description: Limits for CPU and memory usage.
                  properties:
                    cpu:
                      type: string
                      description: Limits for CPU usage.
                      default: 1
                    memory:
                      type: string
                      description: Limits for memory usage.
                      default: 200Mi
            args:
              type: array
              description: Args passed via command-line to sriov-network-device-plugin daemonset.
              items:
                type: string
        sriov_nodes_resources:
          type: array
          description: SR-IOV devices lists on each node specified by node labels.
          items:
            type: string
